#! /usr/bin/env bash

# Script for quickly and effectively rebuilding Nixos, with git tracking

# Maybe implement code style check in the future

# Exit on error
set -e

# Edit current config
HOST=$(hostname)
$EDITOR hosts/${HOST}/configuration.nix

# cd to the config dir
pushd /etc/nixos/

# If no changes were made, exit
if git diff --quiet '*.nix'; then
    echo "No changes were detected. Exiting..."
    popd
    exit 0
fi

# Show changes made
git diff -U0 '*.nix'

echo "Rebuilding NixOS..."

# Rebuild with showing just errors on fail
sudo nixos-rebuild switch --flake . &> nixos-rebuild.log || (cat nixos-rebuild.log | grep --color error && notify-send " Buggy rebuild" "Rebuild failed. Fix your code!"  && exit 1)

# Current generation
current=$(nixos-rebuild list-generations | grep current)

# Commit changes
git commit -am "$current"

# Go back
popd

echo "Rebuild finished!"
if notify-send --version; then
    notify-send " Rebuild finished" "Last rebuild was carried out successfully!"
fi

# Man cache
read -r -p "Do you want to rebuild man-cache? (y/Ctrl-C) " result

# if [ result = "y" ]; then
set -x
sudo mkdir -p /var/cache/man/nixos
sudo mandb
echo "Cashes rebuilt!"
# fi

